SELECT * FROM SALES_DATASET_RFM_PRJ;

-- 1:Chuyển đổi kiểu dữ liệu phù hợp cho các trường ( sử dụng câu lệnh ALTER)
ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER column ordernumber TYPE numeric USING (ordernumber::numeric);

ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER column quantityordered TYPE numeric USING (quantityordered::numeric);

ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER column orderlinenumber TYPE numeric USING (orderlinenumber::numeric);

ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER column msrp TYPE numeric USING (msrp::numeric);

ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER column priceeach TYPE numeric USING (priceeach::numeric);

ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER column sales  TYPE numeric USING (sales::numeric);

ALTER TABLE SALES_DATASET_RFM_PRJ
ALTER column orderdate TYPE date USING (orderdate::date);


--- 2: Check NULL/BLANK (‘’)  ở các trường: ORDERNUMBER, QUANTITYORDERED, PRICEEACH, ORDERLINENUMBER, SALES, ORDERDATE.
SELECT ORDERNUMBER, QUANTITYORDERED, PRICEEACH, ORDERLINENUMBER, SALES, ORDERDATE
FROM SALES_DATASET_RFM_PRJ
WHERE ORDERNUMBER IS NULL 
OR QUANTITYORDERED IS NULL
OR PRICEEACH IS NULL
OR ORDERLINENUMBER IS NULL
OR SALES IS NULL
OR ORDERDATE IS NULL;


--- 3: Thêm cột CONTACTLASTNAME, CONTACTFIRSTNAME được tách ra từ CONTACTFULLNAME . 
-- Chuẩn hóa CONTACTLASTNAME, CONTACTFIRSTNAME theo định dạng chữ cái đầu tiên viết hoa, chữ cái tiếp theo viết thường. 
-- Gợi ý: ( ADD column sau đó UPDATE)
ALTER TABLE SALES_DATASET_RFM_PRJ
ADD COLUMN CONTACTLASTNAME VARCHAR(50);

ALTER TABLE SALES_DATASET_RFM_PRJ
ADD COLUMN CONTACTFIRSTNAME VARCHAR(50);

-- C1: INITCAP
UPDATE SALES_DATASET_RFM_PRJ
SET CONTACTLASTNAME = INITCAP(SUBSTRING (CONTACTFULLNAME FROM POSITION ('-' IN CONTACTFULLNAME) + 1 FOR LENGTH(CONTACTFULLNAME)));
-- C2: 
SELECT UPPER(LEFT(SUBSTRING (CONTACTFULLNAME FROM POSITION ('-' IN CONTACTFULLNAME) + 1 FOR LENGTH(CONTACTFULLNAME)), 1))
|| SUBSTRING (CONTACTFULLNAME FROM POSITION ('-' IN CONTACTFULLNAME) + 2 FOR LENGTH(CONTACTFULLNAME))
FROM SALES_DATASET_RFM_PRJ;

UPDATE SALES_DATASET_RFM_PRJ
SET CONTACTFIRSTNAME = INITCAP(LEFT (CONTACTFULLNAME, POSITION ('-' IN CONTACTFULLNAME) - 1));


--- 4: Thêm cột QTR_ID, MONTH_ID, YEAR_ID lần lượt là Qúy, tháng, năm được lấy ra từ ORDERDATE 
ALTER TABLE SALES_DATASET_RFM_PRJ
ADD COLUMN QTR_ID numeric;

ALTER TABLE SALES_DATASET_RFM_PRJ
ADD COLUMN MONTH_ID numeric;

ALTER TABLE SALES_DATASET_RFM_PRJ
ADD COLUMN YEAR_ID numeric;

UPDATE SALES_DATASET_RFM_PRJ
SET QTR_ID = EXTRACT(QUARTER FROM orderdate);

UPDATE SALES_DATASET_RFM_PRJ
SET MONTH_ID = EXTRACT(MONTH FROM orderdate);

UPDATE SALES_DATASET_RFM_PRJ
SET YEAR_ID = EXTRACT(YEAR FROM orderdate);


--- 5: Hãy tìm outlier (nếu có) cho cột QUANTITYORDERED và hãy chọn cách xử lý cho bản ghi đó (2 cách) ( Không chạy câu lệnh trước khi bài được review)

-- BOXPLOT/ IQR
WITH min_max_value AS
(SELECT 
Q1-1.5*IQR AS min_value,
Q3+1.5*IQR AS max_value 
FROM
(SELECT 
percentile_cont(0.25) WITHIN GROUP (ORDER BY QUANTITYORDERED) AS Q1,
percentile_cont(0.75) WITHIN GROUP (ORDER BY QUANTITYORDERED) AS Q3,
percentile_cont(0.75) WITHIN GROUP (ORDER BY QUANTITYORDERED)-percentile_cont(0.25) WITHIN GROUP (ORDER BY QUANTITYORDERED)
AS IQR
FROM SALES_DATASET_RFM_PRJ) AS a)

SELECT * FROM SALES_DATASET_RFM_PRJ
WHERE QUANTITYORDERED < (SELECT min_value FROM min_max_value)
OR  QUANTITYORDERED > (SELECT max_value FROM min_max_value);

-- Z-SCORE
WITH twt_z_score AS
(SELECT *, 
(SELECT AVG(QUANTITYORDERED) FROM SALES_DATASET_RFM_PRJ) as avg ,
(SELECT stddev(QUANTITYORDERED) FROM SALES_DATASET_RFM_PRJ) as stddev
FROM SALES_DATASET_RFM_PRJ),
twt_outlier AS 
(SELECT *, (QUANTITYORDERED - avg)/stddev AS outliers FROM twt_z_score
WHERE ABS((QUANTITYORDERED - avg)/stddev) > 3)

-- Update các giá trị ngoại lai = giá trị trung bình
UPDATE SALES_DATASET_RFM_PRJ
SET QUANTITYORDERED = (SELECT AVG(QUANTITYORDERED) FROM SALES_DATASET_RFM_PRJ)
WHERE QUANTITYORDERED IN (SELECT QUANTITYORDERED FROM twt_outlier);
-- Hoặc xoá các giá trị ngoại lai khỏi bảng
DELETE FROM SALES_DATASET_RFM_PRJ
WHERE QUANTITYORDERED IN (SELECT QUANTITYORDERED FROM twt_outlier);


--- 6: Sau khi làm sạch dữ liệu, hãy lưu vào bảng mới  tên là SALES_DATASET_RFM_PRJ_CLEAN
CREATE TABLE SALES_DATASET_RFM_PRJ_CLEAN AS
(SELECT * FROM SALES_DATASET_RFM_PRJ);

SELECT * FROM SALES_DATASET_RFM_PRJ_CLEAN;



